name: flustra_template
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  easy_localization: ^3.0.7+1
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  window_manager: ^0.5.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  go_router: ^15.1.3
  flutter_svg: ^2.1.0
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/countries_flags/
    - assets/logo/
    - assets/fonts/cairo/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400



flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#ffffff"
    theme_color: "#007ACC"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 96 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"