import '../app_strings_localizations.dart';

const Map<String, String> arJson = {
  AppStrings.noMoreData: 'لا توجد بيانات أخرى',
  AppStrings.retry: 'إعادة المحاولة',
  AppStrings.somethingWentWrong: 'حدث خطأ ما',
  AppStrings.failedToLoadData: 'تعذر تحميل البيانات. يرجى التحقق من الاتصال والمحاولة مرة أخرى.',
  AppStrings.noInternetConnection: 'لا يوجد اتصال بالإنترنت',
  AppStrings.weakInternetConnection: 'اتصال إنترنت ضعيف',
  AppStrings.reconnecting: 'إعادة الاتصال...',
  AppStrings.internetConnectionRestored: 'تم استعادة الاتصال بالإنترنت',
  AppStrings.noInternet: 'لا يوجد اتصال بالإنترنت',
  AppStrings.connected: 'متصل',
  AppStrings.errorEmptyField: 'هذا الحقل لا يمكن أن يكون فارغًا.',
  AppStrings.errorInvalidEmail: 'يرجى إدخال بريد إلكتروني صالح.',
  AppStrings.errorInvalidPhone: 'أدخل رقم هاتف صالح.',
  AppStrings.errorPasswordTooShort: 'استخدم 6 أحرف على الأقل.',
  AppStrings.errorPasswordNoUppercase: 'أضف حرفًا كبيرًا واحدًا على الأقل.',
  AppStrings.errorPasswordNoLowercase: 'أضف حرفًا صغيرًا واحدًا على الأقل.',
  AppStrings.errorPasswordNoDigit: 'قم بتضمين رقم واحد على الأقل.',
  AppStrings.errorPasswordNoSpecialChar: 'أضف رمزًا خاصًا واحدًا (مثال: !@#).',
  AppStrings.errorPasswordsDoNotMatch: 'كلمتا المرور غير متطابقتين.',
  AppStrings.errorInvalidUsername: 'يجب أن يكون اسم المستخدم من 3 إلى 16 حرفًا، يبدأ بحرف ويستخدم فقط الحروف أو الأرقام أو الشرطة السفلية.',
  AppStrings.errorInvalidFullName: 'أدخل اسمًا صحيحًا',
  AppStrings.errorInvalidUrl: 'أدخل رابطًا (URL) صالحًا.',
  AppStrings.english: 'الانجليزية',
  AppStrings.arabic: 'العربية',
  AppStrings.german: 'الألمانية',
  AppStrings.chooseLanguage: 'اختر اللغة',
  AppStrings.weDidNotReceiveTheExpectedData: 'خطأ في تحميل البيانات. تعذر الاتصال بالخادم. يرجى المحاولة مرة أخرى لاحقًا.',
  AppStrings.errorConnectionTimeout: "انتهت مهلة الاتصال. تحقق من الإنترنت وحاول مرة أخرى.",
  AppStrings.errorSendTimeout: "انتهت مهلة الطلب أثناء إرسال البيانات. حاول مرة أخرى.",
  AppStrings.errorReceiveTimeout: "انتهت مهلة الطلب أثناء انتظار الاستجابة. حاول مرة أخرى.",
  AppStrings.errorBadCertificate: "تعذر التحقق من هوية الخادم. حاول لاحقاً.",
  AppStrings.errorBadResponse: "حدث خطأ في استجابة الخادم. حاول لاحقاً.",
  AppStrings.errorRequestCancelled: "تم إلغاء الطلب. حاول مرة أخرى.",
  AppStrings.errorConnection: "خطأ في الاتصال. تحقق من الشبكة وحاول مجددًا.",
  AppStrings.errorUnknown: "حدث خطأ غير متوقع. حاول مرة أخرى لاحقاً.",
  AppStrings.home: 'الرئيسية',
  AppStrings.leads: 'العملاء المحتملين',
  AppStrings.chat: 'المحادثة',
  AppStrings.alerts: 'التنبيهات',
  AppStrings.settings: 'الإعدادات',
  AppStrings.guest: 'زائر',
  AppStrings.guestDesc: 'يرجى تسجيل الدخول إلى جي تيك',
  AppStrings.admin: 'مسؤول',
  AppStrings.online: 'نشط الآن',
  AppStrings.preferences: 'التفضيلات',
  AppStrings.language: 'اللغة',
  AppStrings.theme: 'المظهر',
  AppStrings.notifications: 'الإشعارات',
  AppStrings.notificationsDesc: 'التنبيهات الفورية وبداخل التطبيق',
  AppStrings.billing: 'الفواتير والاشتراكات',
  AppStrings.billingDesc: 'الخطة الاحترافية • ٤٩\$/شهرياً',
  AppStrings.deleteAccount: 'حذف الحساب',
  AppStrings.deleteAccountDesc: 'هل أنت متأكد من رغبتك في حذف الحساب؟ لا يمكن التراجع عن هذا الإجراء.',
  AppStrings.logout: 'تسجيل الخروج',
  AppStrings.yesLogOut: 'نعم، خروج',
  AppStrings.logoutDesc: 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
  AppStrings.cancel: 'إلغاء',
  AppStrings.yesDelete: 'نعم، حذف',
  AppStrings.darkMode: 'المظهر الداكن',
  AppStrings.lightMode: 'المظهر الفاتح',
  AppStrings.footerBuild: 'قالب فلوسترا • الإصدار ١.٠ • البناء ٢٠٢٦.٠٥',
  AppStrings.login: 'تسجيل الدخول',
  AppStrings.developerOptions: 'خيارات المطورين',
  AppStrings.proxy: 'البروكسي',
  AppStrings.proxyDesc: 'إدارة إعدادات خادم البروكسي لاتصالك',
  AppStrings.themeShowcase: 'عرض الثيمات',
  AppStrings.themeShowcaseDesc: 'استكشاف الثيمات وتصميمات المكونات المتاحة',
  AppStrings.exitApp: 'إغلاق التطبيق',
  AppStrings.exitDesc: 'هل أنت متأكد من رغبتك في الخروج من التطبيق؟',
  AppStrings.exit: 'خروج',
};
