import '../app_strings_localizations.dart';

const Map<String, String> deJson = {
  AppStrings.noMoreData: 'Keine weiteren Daten',
  AppStrings.retry: 'Wiederholen',
  AppStrings.somethingWentWrong: 'Etwas ist schief gelaufen',
  AppStrings.failedToLoadData: 'Daten konnten nicht geladen werden. Bitte überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
  AppStrings.english: 'Englisch',
  AppStrings.arabic: 'Arabisch',
  AppStrings.german: 'Deutsch',
  AppStrings.chooseLanguage: 'Sprache wählen',
  AppStrings.noInternetConnection: 'Keine Internetverbindung',
  AppStrings.weakInternetConnection: 'Schwache Internetverbindung',
  AppStrings.reconnecting: 'Wiederverbindung...',
  AppStrings.internetConnectionRestored: 'Internetverbindung wiederhergestellt',
  AppStrings.noInternet: 'Kein Internet',
  AppStrings.connected: 'Verbunden',
  AppStrings.weDidNotReceiveTheExpectedData: 'Wir haben die erwarteten Daten nicht vom Server erhalten. Bitte versuchen Sie es später erneut.',
  AppStrings.errorConnectionTimeout: 'Verbindungszeitüberschreitung. Bitte überprüfen Sie Ihr Internet und versuchen Sie es erneut.',
  AppStrings.errorSendTimeout: 'Zeitüberschreitung bei der Anfrage während des Sendens der Daten. Bitte versuchen Sie es erneut.',
  AppStrings.errorReceiveTimeout: 'Zeitüberschreitung bei der Anfrage während des Wartens auf eine Antwort. Bitte versuchen Sie es erneut.',
  AppStrings.errorBadCertificate: 'Die Identität des Servers konnte nicht überprüft werden. Bitte versuchen Sie es später erneut.',
  AppStrings.errorBadResponse: 'Etwas ist mit der Serverantwort schiefgelaufen. Bitte versuchen Sie es später erneut.',
  AppStrings.errorRequestCancelled: 'Anfrage wurde abgebrochen. Bitte versuchen Sie es erneut.',
  AppStrings.errorConnection: 'Verbindungsfehler. Bitte überprüfen Sie Ihr Netzwerk und versuchen Sie es erneut.',
  AppStrings.errorUnknown: 'Unerwarteter Fehler aufgetreten. Bitte versuchen Sie es später erneut.',
  AppStrings.errorEmptyField: 'Dieses Feld darf nicht leer sein.',
  AppStrings.errorInvalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
  AppStrings.errorInvalidPhone: 'Geben Sie eine gültige Telefonnummer ein.',
  AppStrings.errorPasswordTooShort: 'Verwenden Sie mindestens 6 Zeichen.',
  AppStrings.errorPasswordNoUppercase: 'Fügen Sie mindestens einen Großbuchstaben hinzu.',
  AppStrings.errorPasswordNoLowercase: 'Fügen Sie mindestens einen Kleinbuchstaben hinzu.',
  AppStrings.errorPasswordNoDigit: 'Fügen Sie mindestens eine Zahl hinzu.',
  AppStrings.errorPasswordNoSpecialChar: 'Fügen Sie ein Sonderzeichen hinzu (z. B. !@#).',
  AppStrings.errorPasswordsDoNotMatch: 'Passwörter stimmen nicht überein.',
  AppStrings.errorInvalidUsername:
      'Der Benutzername muss 3–16 Zeichen lang sein, mit einem Buchstaben beginnen und darf nur Buchstaben, Zahlen oder Unterstriche enthalten.',
  AppStrings.errorInvalidFullName: 'Geben Sie einen gültigen Namen ein',
  AppStrings.errorInvalidUrl: 'Geben Sie einen gültigen Link (URL) ein.',
  AppStrings.home: 'Startseite',
  AppStrings.leads: 'Interessenten',
  AppStrings.chat: 'Chat',
  AppStrings.alerts: 'Meldungen',
  AppStrings.settings: 'Einstellungen',
  AppStrings.guest: 'Gast',
  AppStrings.guestDesc: 'Bitte melden Sie sich bei GTek Solutions an',
  AppStrings.admin: 'Administrator',
  AppStrings.online: 'Online',
  AppStrings.preferences: 'Präferenzen',
  AppStrings.language: 'Sprache',
  AppStrings.theme: 'Thema',
  AppStrings.notifications: 'Benachrichtigungen',
  AppStrings.notificationsDesc: 'Push, In-App • alle Warnungen',
  AppStrings.billing: 'Abrechnung',
  AppStrings.billingDesc: 'Pro-Plan • \$49/Monat',
  AppStrings.deleteAccount: 'Konto löschen',
  AppStrings.deleteAccountDesc: 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
  AppStrings.logout: 'Abmelden',
  AppStrings.yesLogOut: 'Ja, Abmelden',
  AppStrings.logoutDesc: 'Sind Sie sicher, dass Sie sich abmelden möchten?',
  AppStrings.cancel: 'Abbrechen',
  AppStrings.yesDelete: 'Ja, Löschen',
  AppStrings.darkMode: 'Dunkelmodus',
  AppStrings.lightMode: 'Lichtmodus',
  AppStrings.footerBuild: 'Flustra-Vorlage • v1.0 • Build 2026.05',
  AppStrings.login: 'Einloggen',
  AppStrings.developerOptions: 'Entwickleroptionen',
  AppStrings.proxy: 'Proxy',
  AppStrings.proxyDesc: 'Verbindungsproxy-Einstellungen verwalten',
  AppStrings.themeShowcase: 'Theme-Präsentation',
  AppStrings.themeShowcaseDesc: 'Themes und Komponenten-Stile erkunden',
  AppStrings.exitApp: 'App beenden',
  AppStrings.exitDesc: 'Möchten Sie die App wirklich beenden?',
  AppStrings.exit: 'Beenden',
};
