import '../app_strings_localizations.dart';

const Map<String, String> enJson = {
  AppStrings.noMoreData: 'No more data',
  AppStrings.english: 'English',
  AppStrings.arabic: 'Arabic',
  AppStrings.german: 'German',
  AppStrings.chooseLanguage: 'Choose Language',
  AppStrings.noInternetConnection: 'No internet connection',
  AppStrings.weakInternetConnection: 'Weak internet connection',
  AppStrings.reconnecting: 'Reconnecting...',
  AppStrings.internetConnectionRestored: 'Internet connection restored',
  AppStrings.noInternet: 'No internet',
  AppStrings.connected: 'Connected',
  AppStrings.weDidNotReceiveTheExpectedData: 'Error loading data. Could not connect to the server. Please try again later',
  AppStrings.errorConnectionTimeout: "Connection timed out. Please check your internet and try again.",
  AppStrings.errorSendTimeout: "Request timed out while sending data. Please try again.",
  AppStrings.errorReceiveTimeout: "Request timed out while waiting for response. Please try again.",
  AppStrings.errorBadCertificate: "Could not verify the server's identity. Please try again later.",
  AppStrings.errorBadResponse: "Something went wrong with the server response. Please try again later.",
  AppStrings.errorRequestCancelled: "Request was cancelled. Please try again.",
  AppStrings.errorConnection: "Connection error. Please check your network and try again.",
  AppStrings.errorUnknown: "Unexpected error occurred. Please try again later.",
  AppStrings.errorEmptyField: "This field can't be empty.",
  AppStrings.errorInvalidEmail: "Please enter a valid email.",
  AppStrings.errorInvalidPhone: "Enter a valid phone number.",
  AppStrings.errorPasswordTooShort: "Use at least 6 characters.",
  AppStrings.errorPasswordNoUppercase: "Add at least one capital letter.",
  AppStrings.errorPasswordNoLowercase: "Add at least one lowercase letter.",
  AppStrings.errorPasswordNoDigit: "Include at least one number.",
  AppStrings.errorPasswordNoSpecialChar: "Add one special character (e.g. !@#).",
  AppStrings.errorPasswordsDoNotMatch: "Passwords don’t match.",
  AppStrings.errorInvalidUsername: "Username must be 3–16 characters, start with a letter, and use only letters, numbers, or underscores.",
  AppStrings.errorInvalidFullName: "Enter valid name",
  AppStrings.errorInvalidUrl: "Enter a valid link (URL).",
  AppStrings.home: 'Home',
  AppStrings.leads: 'Leads',
  AppStrings.chat: 'Chat',
  AppStrings.alerts: 'Alerts',
  AppStrings.settings: 'Settings',
  AppStrings.guest: 'Guest',
  AppStrings.guestDesc: 'Please login to GTek Solutions',
  AppStrings.admin: 'Admin',
  AppStrings.online: 'Online',
  AppStrings.preferences: 'Preferences',
  AppStrings.language: 'Language',
  AppStrings.theme: 'Theme',
  AppStrings.notifications: 'Notifications',
  AppStrings.notificationsDesc: 'Push, in-app • all alerts',
  AppStrings.billing: 'Billing',
  AppStrings.billingDesc: 'Pro plan • \$49/mo',
  AppStrings.deleteAccount: 'Delete Account',
  AppStrings.deleteAccountDesc: 'Are you sure you want to delete your account? This action cannot be undone.',
  AppStrings.logout: 'Logout',
  AppStrings.yesLogOut: 'Yes, Logout',
  AppStrings.logoutDesc: 'Are you sure you want to log out?',
  AppStrings.cancel: 'Cancel',
  AppStrings.yesDelete: 'Yes, Delete',
  AppStrings.darkMode: 'Dark Mode',
  AppStrings.lightMode: 'Light Mode',
  AppStrings.footerBuild: 'Flustra Template • v1.0 • Build 2026.05',
  AppStrings.login: 'Login',
  AppStrings.developerOptions: 'Developer Options',
  AppStrings.proxy: 'Proxy',
  AppStrings.proxyDesc: 'Manage connection proxy settings',
  AppStrings.themeShowcase: 'Theme Showcase',
  AppStrings.themeShowcaseDesc: 'Explore themes and component styles',
  AppStrings.exitApp: 'Exit App',
  AppStrings.exitDesc: 'Are you sure you want to exit the application?',
  AppStrings.exit: 'Exit',
};
